matrix:

	python MatrixGenerator.py File1ForLab3.txt File2ForLab3.txt

algorithm1:

	python MatrixMultiply1.py File1ForLab3.txt File2ForLab3.txt

algorithm2:

	python3 MatrixMultiply2.py File1ForLab3.txt File2ForLab3.txt
